let productsDB = [
    {
        id: 1,
        title: "iPhone 12 Pro Max 256GB Pacific Blue",
        imgUrl: "images/1.jpg",
        rate: "❤❤❤❤🤍",
        price: 23555,
        qty : 1,
    },
    {
        id: 2,
        title: "iPhone 13 Pro Max 256GB Sierra Blue",
        imgUrl: "images/2.jpg",
        rate: "❤❤❤❤❤",
        price: 26123,
        qty : 1,
    },
    {
        id: 3,
        title: "iPhone 13 128GB Blue",
        imgUrl: "images/3.jpg",
        rate: "❤❤🤍🤍🤍",
        price: 16466,
        qty : 1,
    },
    {
        id: 4,
        title: "Apple iPhone XS  Facetime - 256 GB",
        imgUrl: "images/4.jpg",
        rate: "❤❤❤🤍🤍",
        price: 12255,
        qty : 1,
    },
    // row 1 
    {
        id: 5,
        title: "Samsung Galaxy A52s - 128GB, Black",
        imgUrl: "images/5.jpg",
        rate: "❤❤❤❤❤",
        price: 7555,
        qty : 1,
    },
    {
        id: 6,
        title: "Samsung Galaxy A12 - 6.5 Inch, Black",
        imgUrl: "images/6.jpg",
        rate: "❤❤❤❤❤",
        price: 2677,
        qty : 1,
    },
    {
        id: 7,
        title: "Samsung Galaxy A52s- Awesome Mint",
        imgUrl: "images/7.jpg",
        rate: "❤❤🤍🤍🤍",
        price: 7899,
        qty : 1,
    },
    {
        id: 8,
        title: "Samsung Galaxy S21 Ultra- Silver",
        imgUrl: "images/8.jpg",
        rate: "❤❤❤🤍🤍",
        price: 20202,
        qty : 1,
    },
    // row 2 
    {
        id: 9,
        title: "Huawei Y6p - 64 GB Emerald Green",
        imgUrl: "images/9.jpg",
        rate: "❤❤❤❤❤",
        price: 2404,
        qty : 1,
    },
    {
        id: 10,
        title: "Huawei Y5p Dual SIM - 32GB",
        imgUrl: "images/10.jpg",
        rate: "❤❤❤❤🤍",
        price: 1705,
        qty : 1,
    },
    {
        id: 11,
        title: "Huawei Nova 7 - 256GB, Space Silver",
        imgUrl: "images/11.jpg",
        rate: "❤❤❤❤🤍",
        price: 7055,
        qty : 1,
    },
    {
        id: 12,
        title: "Huawei P40- 128GB, 8GB RAM, Black",
        imgUrl: "images/12.jpg",
        rate: "❤❤❤🤍🤍",
        price: 15405,
        qty : 1,
    },
];

localStorage.setItem('products', JSON.stringify(productsDB));